import { expandedTracks, expandedLessons, sourceGroups } from './expandedContent.js';
export const tracks = expandedTracks;

const baseLessons = {
  'what-is-ai': { title:'What is artificial intelligence?', time:'8 min', hook:'How can a machine make a useful prediction without being told every rule?', intuition:'Imagine teaching someone to recognize apples by showing many examples. Instead of writing a rule for every apple, you help them notice patterns.', simple:'AI is a broad name for computer systems that do tasks we associate with intelligence, such as recognizing patterns, making predictions, or generating text.', technical:'In modern machine learning, a model maps an input to an output using parameters learned from data. AI also includes methods that do not learn from data.', example:'A spam filter uses patterns in past email to estimate whether a new message is spam.', mistake:'AI does not “understand” or reason in one single universal way. Different systems use different methods and have different limits.', terms:['model','training','inference'], visual:'pipeline', question:'What does a learned model use to make a prediction?', answers:['Patterns captured in its parameters','A handwritten rule for every possible input','Random selection only'], correct:0, takeaway:['AI is a broad field, not one product.','A model connects inputs to outputs.','Examples and evaluation matter.'] },
  'data-and-models': { title:'Data, features & models', time:'9 min', hook:'What does a model actually learn from?', intuition:'Data is a collection of examples. A feature is one detail you decide to show the model, like the size of a house.', simple:'A model learns a pattern from examples and then applies it to new inputs. The quality and relevance of those examples strongly affect its results.', technical:'A dataset contains observations. Features describe each observation; labels are desired outputs in supervised learning. Parameters are values the training process adjusts.', example:'To estimate a home price, features might include floor area and location; the label is the sale price.', mistake:'More data is not automatically better if it is inaccurate, biased, or unlike the real cases the model will face.', terms:['data','feature','label','model'], visual:'data', question:'In a labeled house-price dataset, what is the label?', answers:['The sale price','The floor area','The model architecture'], correct:0, takeaway:['Data consists of examples.','Features describe inputs; labels are target outputs.','Data quality shapes model behavior.'] },
  'training-and-inference': { title:'Training vs inference', time:'8 min', hook:'When is the model learning, and when is it simply being used?', intuition:'Training is like practicing with feedback. Inference is like taking the test using what you already learned.', simple:'During training, a system adjusts model parameters using examples. During inference, it uses those parameters to produce an answer for a new input.', technical:'Training typically computes a loss and parameter gradients, then updates weights. Inference runs a forward pass with fixed weights; some systems may also use external context or tools.', example:'A photo classifier trains on labeled images, then infers a category for a newly uploaded photo.', mistake:'Sending a prompt to a model normally does not train its weights in that request.', terms:['training','inference','parameter'], visual:'toggle', question:'What usually changes during training?', answers:['Model parameters','The user’s screen size','Nothing'], correct:0, takeaway:['Training updates weights.','Inference uses learned weights.','The two phases have different cost and behavior.'] },
  'tokens': { title:'From text to tokens', time:'9 min', hook:'How can a model process a sentence if it only works with numbers?', intuition:'A tokenizer is a translator that cuts text into pieces and gives each piece an ID.', simple:'Before a language model processes text, a tokenizer splits it into tokens. Tokens can be whole words, word parts, spaces, or punctuation.', technical:'A tokenizer maps text to IDs from a fixed vocabulary. Its segmentation affects context length and cost. The model receives token IDs, not raw characters.', example:'“unbelievable” might be one token in one vocabulary and several tokens in another.', mistake:'One token is not always one word. Token counts vary by language, spelling, and tokenizer.', terms:['token','tokenizer','vocabulary'], visual:'tokenizer', question:'Which statement about tokens is true?', answers:['A token may be part of a word','Every token is exactly one word','Tokens are always sentences'], correct:0, takeaway:['Models receive token IDs.','Token boundaries depend on the tokenizer.','Token count affects context and cost.'] },
  'embeddings': { title:'Embeddings: meaning as coordinates', time:'11 min', hook:'How can numbers represent similarity between words?', intuition:'Imagine every word has an address on a map. Related ideas tend to have useful relationships on that map.', simple:'An embedding is a list of numbers that represents a token or another item so a model can work with it.', technical:'An embedding layer looks up a learned vector for each token ID. These vectors are adjusted during training. Similarity in vector space can be useful, but interpretation depends on the model and task.', example:'A search system can compare query and document embeddings to find related content.', mistake:'An embedding is not a dictionary definition hidden inside a vector. Its meaning comes from learned relationships and context.', terms:['embedding','vector','dimension'], visual:'embedding', question:'What is an embedding?', answers:['A numeric vector representing an item','The original word stored as plain text','A database table only'], correct:0, takeaway:['Embeddings are numeric vectors.','They let models operate on discrete items.','Their relationships are learned.'] },
  'attention': { title:'Attention: choosing context', time:'12 min', hook:'When a sentence says “it,” which earlier word matters?', intuition:'Each word can ask: which other words should I pay attention to right now?', simple:'Self-attention lets each token combine information from other tokens in its context.', technical:'Tokens form query, key, and value vectors. Query-key scores are normalized into weights; the weighted sum of values produces a context-aware representation. A causal mask prevents a decoder from looking ahead.', example:'In “The cat slept because it was tired,” the token “it” can draw information from “cat.”', mistake:'An attention weight is not a complete explanation of everything a model knows or why it answered.', terms:['attention','query','key','value'], visual:'attention', question:'What does self-attention help a token do?', answers:['Use information from other relevant tokens','Change the model’s weights during every request','Store a webpage in a database'], correct:0, takeaway:['Tokens exchange contextual information.','Queries and keys help determine weights.','Values provide information to combine.'] },
  'prompts': { title:'Prompts as clear instructions', time:'8 min', hook:'Why do two prompts for the same task give different results?', intuition:'A prompt is a brief for a collaborator. Clear goals, context, and format reduce guesswork.', simple:'A prompt provides the model with instructions and context for the task at hand.', technical:'Prompt design specifies task, relevant input, constraints, examples, and desired output shape. It should be evaluated on representative cases rather than judged from one response.', example:'“Summarize this for a busy manager in three bullets, preserving dates and open risks” gives more guidance than “Summarize this.”', mistake:'A polished prompt does not replace factual grounding, validation, or application safeguards.', terms:['prompt','context','evaluation'], visual:'prompt', question:'Which prompt detail makes output easier to use?', answers:['A specified audience and output format','A vague request','Unrelated examples'], correct:0, takeaway:['State the task and audience.','Provide relevant context.','Evaluate on multiple cases.'] },
  'rag': { title:'RAG: retrieve before answering', time:'11 min', hook:'How can a model answer from a document it was never trained on?', intuition:'Before writing an answer, let it look up the relevant pages—like an open-book exam.', simple:'Retrieval-augmented generation (RAG) finds useful source material and supplies it to a model with the question.', technical:'A typical pipeline parses documents, chunks them, indexes them, retrieves candidates, optionally reranks them, and adds selected passages to the generation context with citations.', example:'A support assistant retrieves the current refund policy before answering a customer question.', mistake:'RAG does not guarantee correctness. Retrieval can miss the right passage, and the model can still misread it.', terms:['rag','retrieval','chunk','embedding'], visual:'rag', question:'What happens before generation in a RAG system?', answers:['Relevant source passages are retrieved','Model weights must be retrained','The answer is always known already'], correct:0, takeaway:['RAG supplies external context.','Retrieval quality matters.','Citations help users verify answers.'] },
  'agents': { title:'Agents, tools & decisions', time:'10 min', hook:'What changes when a model can take an action?', intuition:'An agent is a model in a loop: decide what to do, use a tool, inspect the result, and continue.', simple:'An AI agent can choose actions using available tools and observations to pursue a goal.', technical:'An agent runtime manages model calls, tool schemas, execution, state, stopping conditions, and human approval for consequential actions. Reliability depends on bounded tools and evaluation.', example:'A scheduling assistant can check a calendar, propose a free time, and create an event after approval.', mistake:'More tools and longer loops do not automatically make an agent better. They can increase errors and cost.', terms:['agent','tool','observation'], visual:'agent', question:'What should happen after an agent uses a tool?', answers:['It observes the tool result and decides the next step','It assumes the action succeeded','It ignores the result'], correct:0, takeaway:['Agents act in a loop.','Tools connect models to external systems.','Boundaries and checks are essential.'] },
  'request-path': { title:'The inference request path', time:'12 min', hook:'What happens between pressing Enter and seeing the first word?', intuition:'A request is a journey through several stations: prepare input, run the model, choose output, stream it back.', simple:'Inference engineering is the work of running a trained model quickly, reliably, and efficiently for users.', technical:'A service applies a chat template and tokenizer, schedules the request, runs prefill for the prompt, decodes output tokens, samples and stops, then streams a response while tracking memory and latency.', example:'A chat API must handle concurrent prompts, cancellation, GPU memory limits, and streaming.', mistake:'Wrapping a model in an HTTP endpoint alone does not solve scheduling, memory, or measurement.', terms:['inference','prefill','decode','latency'], visual:'request', question:'Which phase processes the prompt before generating output tokens?', answers:['Prefill','Decode','Rendering CSS'], correct:0, takeaway:['Follow the entire request path.','Prefill handles the prompt.','Serving adds scheduling and reliability.'] },
  'decode-loop': { title:'Generation is a loop', time:'11 min', hook:'Why does an answer appear one piece at a time?', intuition:'The model writes one token, reads the growing sentence, then chooses the next.', simple:'A language model commonly generates output tokens one at a time, feeding each new token back into the next step.', technical:'Each decode step produces logits for the next token. A sampling rule selects a token, stop conditions are checked, and the loop continues. Time to first token and time per output token describe different parts of the experience.', example:'A 200-token answer requires many sequential decode steps even when the prompt was processed in parallel.', mistake:'One model forward pass does not normally produce the entire final answer.', terms:['decode','logits','sampling','tpot'], visual:'decode', question:'Why is output generation sequential?', answers:['Each new token influences the next step','The browser cannot show more than one word','Training happens between every token'], correct:0, takeaway:['Generation repeats a forward step.','Sampling selects the next token.','Long outputs increase decode time.'] },
  'kv-cache': { title:'KV cache: memory for context', time:'12 min', hook:'Why not reread every earlier token from scratch each time?', intuition:'Keep useful notes from earlier steps so the model can reuse them.', simple:'A KV cache stores attention key and value states for tokens already processed, reducing repeated computation during generation.', technical:'The cache grows with sequence length, layers, attention heads, head dimension, and bytes per element. Serving many long requests makes cache memory a major scheduling constraint.', example:'A server can reuse earlier attention states while producing each next token in a streamed answer.', mistake:'KV cache is not the same as the model’s learned weights, and caching does not make memory use free.', terms:['kv-cache','attention','memory','decode'], visual:'cache', question:'What does the KV cache mainly avoid?', answers:['Recomputing attention states for previous tokens','Storing model weights','Tokenizing the final display text'], correct:0, takeaway:['KV cache reuses prior attention state.','It grows as context grows.','Memory capacity limits concurrency.'] }
};

const baseGlossary = {
  model:'A system that maps an input to an output using learned or designed rules.', training:'The process of adjusting model parameters using examples and feedback.', inference:'Using a trained model to produce an output for a new input.', data:'Examples or observations used to build, test, or run a system.', feature:'A measurable property supplied as an input to a model.', label:'The desired output attached to a training example.', parameter:'A value inside a model that training can adjust.', token:'A piece of text represented by an ID for a language model.', tokenizer:'Software that converts text into tokens and token IDs.', vocabulary:'The set of token IDs a tokenizer knows.', embedding:'A numeric vector learned to represent an item.', vector:'An ordered list of numbers.', dimension:'One coordinate in a vector.', attention:'A way for tokens to combine information from other tokens.', query:'A vector representing what a token seeks from context.', key:'A vector used to score how relevant a token is to a query.', value:'A vector whose information is combined using attention weights.', prompt:'Instructions and context sent to a model.', context:'Information available to a model for its current task.', evaluation:'Testing how well a system performs on representative cases.', rag:'Retrieval-augmented generation: supplying retrieved sources before a model answers.', retrieval:'Finding relevant information from a collection.', chunk:'A segment of a document prepared for indexing or retrieval.', agent:'A system that can choose actions and use tools in a loop.', tool:'An external function or service that a model-driven system can call.', observation:'Information returned after an action or tool call.', prefill:'The inference phase that processes the input prompt.', decode:'The repeated phase that produces output tokens.', latency:'The time a user waits for a response or part of it.', logits:'Raw scores a model produces for possible next tokens.', sampling:'A method for choosing the next token from model scores.', tpot:'Time per output token: the pace of generated tokens.', 'kv-cache':'Stored attention key and value states from earlier tokens.', memory:'Storage used by model weights, cache, and active computation.'
};
export const lessons = { ...baseLessons, ...expandedLessons };
// Keep checks meaningful: the correct choice should not always be option A.
for (const [id,lesson] of Object.entries(lessons)) {
  const shift = [...id].reduce((sum,char)=>sum+char.charCodeAt(0),0)%lesson.answers.length;
  lesson.answers = [...lesson.answers.slice(-shift),...lesson.answers.slice(0,-shift)];
  lesson.correct = (lesson.correct+shift)%lesson.answers.length;
}
const originalSources = {
  'what-is-ai':sourceGroups.ml,'data-and-models':sourceGroups.ml,'training-and-inference':sourceGroups.ml,
  tokens:sourceGroups.transformers,embeddings:sourceGroups.transformers,attention:sourceGroups.transformers,
  prompts:sourceGroups.openai,rag:sourceGroups.transformers,agents:sourceGroups.mcp,
  'request-path':sourceGroups.inference,'decode-loop':sourceGroups.inference,'kv-cache':sourceGroups.inference
};
for (const [id,sources] of Object.entries(originalSources)) lessons[id].sources=sources;
export const glossary = { ...baseGlossary,
  algorithm:'A precise set of steps for solving a problem.',
  'neural network':'Layers of numerical functions whose weights can be trained from data.',
  python:'A general-purpose programming language widely used in AI engineering.',
  function:'A reusable mapping from inputs to an output.',
  list:'An ordered Python collection of values.',
  dictionary:'A Python collection that maps keys to values.',
  probability:'A number from 0 to 1 that represents uncertainty under a model.',
  gradient:'A collection of slopes showing how a result changes with parameters.',
  loss:'A number that measures how poorly a prediction matches a target.',
  regression:'A machine-learning task that predicts a continuous number.',
  classification:'A machine-learning task that predicts a category.',
  overfitting:'Fitting training quirks that fail to generalize to new data.',
  precision:'The fraction of predicted positives that are correct.',
  recall:'The fraction of real positives that a system finds.',
  neuron:'A weighted sum of inputs followed by an activation.',
  activation:'A function applied to a layer output, often adding nonlinearity.',
  batch:'A group of training examples processed in one update.',
  epoch:'One pass through the training dataset.',
  optimizer:'An update rule that changes model parameters using gradients.',
  corpus:'A collection of text used for analysis or training.',
  'tf-idf':'A weighting method that emphasizes terms distinctive to a document.',
  transformer:'A neural-network architecture that mixes information through attention blocks.',
  'causal mask':'A rule that prevents a token from attending to future tokens.',
  'context window':'The token budget a model can use within a request.',
  temperature:'A setting that changes the sharpness of next-token probabilities.',
  'fine-tuning':'Further training a pretrained model for a target behavior or task.',
  hallucination:'Generated content that is false or unsupported by the available evidence.',
  'prompt injection':'Instructions planted in lower-trust content to redirect an AI system.',
  'cosine similarity':'A score comparing the direction of two nonzero vectors.',
  'vector index':'A structure that accelerates nearest-neighbor search over vectors.',
  reranking:'Scoring a small retrieved candidate set again with a more careful model.',
  schema:'A contract describing the expected shape and types of data.',
  api:'An interface that lets programs send requests and receive responses.',
  'rate limit':'A bound on how many requests a user or service can make in a period.',
  'time to first token':'The wait from request start until the first generated token arrives.',
  throughput:'The amount of work completed per unit of time.',
  quantization:'Representing model values with fewer bits to reduce resource use.',
  'continuous batching':'Scheduling active generation requests together as they arrive and finish.',
  diffusion:'A generative approach that iteratively removes noise from a representation.'
};
export const lessonIds = tracks.flatMap(t => t.lessons);
export const findTrack = lessonId => tracks.find(t => t.lessons.includes(lessonId));
