// Final exam: 50 questions mixed across every module. These are written for
// the exam and are not reused from the lesson quizzes. `answer` is the index
// of the correct option; options are shuffled when shown.
// This file is loaded by the server only (api/exam.js). Pages use ./examMeta.js.

export const examQuestions = [
  // Foundations and machine learning
  { topic: 'Starter Kit', q: 'A team wants a chatbot to answer from its own policy documents, which change every week. Which approach fits best?', options: ['Retrieval-augmented generation over the documents', 'Fine-tuning the model once on the documents', 'Quantizing the model to 4 bits', 'Raising the sampling temperature'], answer: 0, explain: 'RAG fetches current documents at question time, so weekly changes need no retraining.' },
  { topic: 'ML Basics', q: 'A model scores 99% on training data and 71% on unseen data. What is the most likely problem?', options: ['Underfitting', 'Overfitting', 'Data leakage into the test set', 'A learning rate that is too low'], answer: 1, explain: 'A large gap between training and unseen performance means the model memorised the training set.' },
  { topic: 'ML Basics', q: 'You must group customers by behaviour and have no labels at all. Which family of methods applies?', options: ['Supervised classification', 'Supervised regression', 'Unsupervised clustering', 'Reinforcement learning'], answer: 2, explain: 'Clustering finds structure in unlabelled data.' },
  { topic: 'ML Basics', q: 'A cancer screening test must miss as few real cases as possible, even at the cost of more false alarms. Which metric should it favour?', options: ['Precision', 'Recall', 'Accuracy', 'Specificity'], answer: 1, explain: 'Recall measures the share of real positives that are caught.' },
  { topic: 'ML Basics', q: 'Compared with L2 (squared) loss, L1 (absolute) loss is:', options: ['More sensitive to outliers', 'Less sensitive to outliers', 'Undefined for negative errors', 'Always larger for small errors below 1 in every case, so it trains faster'], answer: 1, explain: 'Squaring magnifies large errors, so L2 reacts strongly to outliers; L1 grows only linearly.' },
  { topic: 'ML Basics', q: 'Which regulariser tends to drive many weights exactly to zero, giving a sparse model?', options: ['L2 (ridge)', 'L1 (lasso)', 'Dropout', 'Batch normalisation'], answer: 1, explain: 'The L1 penalty has a constant pull toward zero, which zeroes out weak weights.' },
  { topic: 'ML Basics', q: 'Logistic regression outputs a value between 0 and 1 because it applies which function to a linear score?', options: ['ReLU', 'Softmax over the batch', 'Sigmoid', 'Tanh'], answer: 2, explain: 'The sigmoid squashes any real number into the range 0 to 1.' },
  { topic: 'ML Basics', q: 'In reinforcement learning, what does the agent try to maximise?', options: ['The immediate reward of each single step only', 'The expected cumulative reward over time', 'The number of distinct states visited', 'The size of the action space'], answer: 1, explain: 'The objective is long-run (usually discounted) return, not just the next reward.' },
  // Deep learning
  { topic: 'Neural Nets', q: 'Why does a neural network need non-linear activation functions between layers?', options: ['To make training use less memory', 'Without them, stacked layers collapse into a single linear map', 'To keep weights positive', 'To remove the need for a loss function'], answer: 1, explain: 'A composition of linear layers is still linear, so depth would add no expressive power.' },
  { topic: 'Neural Nets', q: 'Backpropagation computes gradients efficiently by applying which rule layer by layer?', options: ['Bayes’ rule', 'The chain rule', 'The product rule of probability', 'L’Hôpital’s rule'], answer: 1, explain: 'The chain rule lets each layer reuse the gradient passed back from the layer after it.' },
  { topic: 'Neural Nets', q: 'With a learning rate that is far too high, gradient descent typically:', options: ['Converges slowly but surely', 'Overshoots and the loss diverges or oscillates', 'Stops at the first local minimum', 'Has no effect on the weights'], answer: 1, explain: 'Steps larger than the curvature allows jump past the minimum and can blow up.' },
  { topic: 'Neural Nets', q: 'Dropout is switched off at inference time because:', options: ['It only works on GPUs', 'Randomly removing units would make predictions noisy; the full network is used instead', 'It doubles the number of parameters', 'Inference has no activations'], answer: 1, explain: 'Dropout is a training-time regulariser; at inference all units are kept.' },
  { topic: 'Neural Nets', q: 'For a classifier, cross-entropy loss is smallest when:', options: ['The model gives probability near 1 to the correct class', 'All classes receive equal probability', 'The logits are all zero', 'The model gives probability near 0 to the correct class'], answer: 0, explain: 'Cross-entropy is the negative log of the probability assigned to the true class.' },
  { topic: 'Neural Nets', q: 'The main weakness of plain RNNs on long sequences, which attention later addressed, is:', options: ['They cannot process text', 'Information from early tokens fades and gradients vanish over many steps', 'They require labelled data', 'They have no weights'], answer: 1, explain: 'Passing state through many steps loses early information and shrinks gradients.' },
  // Transformers
  { topic: 'Transformers', q: 'Subword tokenisers such as BPE are preferred over whole-word vocabularies mainly because they:', options: ['Make the model deterministic', 'Handle rare and unseen words by splitting them into known pieces', 'Remove the need for embeddings', 'Guarantee one token per word'], answer: 1, explain: 'Any word can be built from subword units, so there is no out-of-vocabulary failure.' },
  { topic: 'Transformers', q: 'In scaled dot-product attention, the scores are divided by √dₖ in order to:', options: ['Make attention causal', 'Keep the dot products from growing so large that softmax saturates', 'Reduce the vocabulary size', 'Add positional information'], answer: 1, explain: 'Large dot products push softmax into regions with tiny gradients; scaling keeps them moderate.' },
  { topic: 'Transformers', q: 'A causal (look-ahead) mask in a decoder ensures that a token can attend to:', options: ['Only itself', 'Itself and earlier tokens, never later ones', 'Only later tokens', 'Every token in the batch'], answer: 1, explain: 'Masking future positions lets the model be trained to predict the next token honestly.' },
  { topic: 'Transformers', q: 'Why does a Transformer need positional information added to its token embeddings?', options: ['Attention on its own has no notion of token order', 'To shrink the embedding dimension', 'To replace the feed-forward layers', 'Because tokens are processed one at a time'], answer: 0, explain: 'Self-attention treats its inputs as a set, so order must be injected.' },
  { topic: 'Transformers', q: 'Multi-head attention uses several heads so that the model can:', options: ['Use fewer parameters than one head', 'Attend to different kinds of relationships in parallel', 'Avoid using softmax', 'Process tokens sequentially'], answer: 1, explain: 'Each head learns its own projection and can track a different pattern.' },
  { topic: 'Transformers', q: 'In a Transformer block, the feed-forward network is applied:', options: ['Across tokens, mixing information between positions', 'To each token position independently', 'Only to the first token', 'Only during training'], answer: 1, explain: 'Attention mixes tokens; the feed-forward layer transforms each position on its own.' },
  // Generation
  { topic: 'Output Pipeline', q: 'Lowering the sampling temperature toward 0 makes the output:', options: ['More random and diverse', 'More deterministic, favouring the most likely tokens', 'Longer', 'Cheaper per token'], answer: 1, explain: 'A low temperature sharpens the distribution toward the top token.' },
  { topic: 'Output Pipeline', q: 'Top-p (nucleus) sampling with p = 0.9 keeps:', options: ['The 9 most likely tokens', 'The smallest set of tokens whose probabilities add up to at least 0.9', 'Tokens with probability above 0.9', 'A random 90% of the vocabulary'], answer: 1, explain: 'The nucleus grows or shrinks with how confident the model is.' },
  { topic: 'Output Pipeline', q: 'The "lost in the middle" effect means a model tends to:', options: ['Forget its system prompt entirely', 'Use information at the start and end of a long context better than information in the middle', 'Stop generating halfway', 'Ignore the last message'], answer: 1, explain: 'Recall follows a U-shape over position in a long context.' },
  // Modern architecture and model types
  { topic: 'Modern Architectures', q: 'In a Mixture-of-Experts model, the router’s job is to:', options: ['Pick a small subset of expert networks to run for each token', 'Average the outputs of every expert for every token', 'Tokenise the input', 'Cache keys and values'], answer: 0, explain: 'Only the selected experts run, so capacity grows without running every parameter.' },
  { topic: 'Modern Architectures', q: 'Grouped-query attention reduces memory at inference mainly by:', options: ['Removing the feed-forward layer', 'Sharing key and value heads across groups of query heads, shrinking the KV cache', 'Using 1-bit weights', 'Dropping positional encoding'], answer: 1, explain: 'Fewer key/value heads means fewer cached tensors per token.' },
  { topic: 'Model Types', q: 'A small language model is often the better choice when:', options: ['The task is narrow and latency, cost or on-device use matter', 'The task needs the broadest possible world knowledge', 'No evaluation data exists', 'Outputs must be as creative as possible'], answer: 0, explain: 'Small models are cheaper and faster and can match large ones on focused tasks.' },
  // Training and alignment
  { topic: 'Training & Alignment', q: 'LoRA makes fine-tuning cheap by:', options: ['Training every weight at lower precision', 'Freezing the original weights and training small low-rank matrices added to them', 'Deleting attention heads', 'Training only the tokenizer'], answer: 1, explain: 'The update is expressed as a product of two small matrices, so few parameters are trained.' },
  { topic: 'Training & Alignment', q: 'In knowledge distillation, the student model learns from:', options: ['Only the hard labels in the dataset', 'The teacher model’s output distribution (soft targets)', 'Random noise', 'The teacher’s tokenizer only'], answer: 1, explain: 'Soft targets carry information about how the teacher ranks the wrong answers too.' },
  { topic: 'Training & Alignment', q: 'RLHF and DPO are both used to:', options: ['Compress a model', 'Align a model’s behaviour with human preferences', 'Speed up tokenisation', 'Build a vector index'], answer: 1, explain: 'Both use human preference data; DPO does so without a separate reward model or RL loop.' },
  { topic: 'Training & Alignment', q: 'Fine-tuning is usually a better tool than RAG when the goal is to:', options: ['Answer from documents that change daily', 'Teach a consistent style, format or skill the base model lacks', 'Cite the source of each fact', 'Reduce the context length to zero'], answer: 1, explain: 'Fine-tuning changes behaviour; RAG supplies changing knowledge.' },
  // Prompting
  { topic: 'Prompt Engineering', q: 'Chain-of-thought prompting improves results on multi-step problems by:', options: ['Shortening the answer', 'Having the model work through intermediate reasoning steps before answering', 'Removing the system prompt', 'Lowering the temperature to zero'], answer: 1, explain: 'Writing out steps gives the model room to compute intermediate results.' },
  { topic: 'Prompt Engineering', q: 'Prompt caching reduces cost and latency when:', options: ['Every request has a completely different prompt', 'Many requests share a long identical prefix', 'The model is quantized', 'Outputs are streamed'], answer: 1, explain: 'The shared prefix is processed once and reused across requests.' },
  // RAG
  { topic: 'RAG Systems', q: 'In a RAG pipeline, documents are split into chunks mainly so that:', options: ['The embedding model trains faster', 'Retrieval can return focused passages that fit in the context window', 'The vector database uses less disk', 'The LLM can be fine-tuned'], answer: 1, explain: 'Chunks give retrieval a useful unit: small enough to be specific, large enough to carry meaning.' },
  { topic: 'RAG Systems', q: 'Approximate nearest-neighbour indexes such as IVF or HNSW trade a little recall for:', options: ['Much faster search over large collections', 'Higher embedding dimension', 'Exact results', 'Smaller chunks'], answer: 0, explain: 'They avoid comparing the query with every vector.' },
  { topic: 'RAG Systems', q: 'Hybrid search combines:', options: ['Two different LLMs', 'Keyword (lexical) search and vector (semantic) search', 'Fine-tuning and distillation', 'Top-k and top-p sampling'], answer: 1, explain: 'Lexical search catches exact terms; vector search catches meaning. Fusing them covers both.' },
  { topic: 'RAG Systems', q: 'A reranker is added after first-stage retrieval in order to:', options: ['Generate the final answer', 'Re-score the candidates more accurately and keep the best few', 'Embed the documents', 'Split documents into chunks'], answer: 1, explain: 'A slower, more precise model orders a short candidate list.' },
  // Agents
  { topic: 'AI Agents', q: 'What turns an LLM call into an agent?', options: ['A larger context window', 'A loop in which the model chooses actions (such as tool calls), observes results and continues', 'A lower temperature', 'A vector database'], answer: 1, explain: 'The defining feature is the act-observe loop driven by the model’s own decisions.' },
  { topic: 'AI Agents', q: 'In function calling, the model’s role is to:', options: ['Execute the function inside its own weights', 'Output a structured request naming a function and arguments, which the application runs', 'Compile the function', 'Store the function’s results permanently'], answer: 1, explain: 'The model only proposes the call; your code executes it and returns the result.' },
  { topic: 'AI Agents', q: 'The Model Context Protocol (MCP) standardises:', options: ['How models are quantized', 'How applications expose tools and data sources to models', 'How tokens are sampled', 'How GPUs schedule batches'], answer: 1, explain: 'MCP gives tools and data a common interface so any compatible client can use them.' },
  { topic: 'Agent Frameworks', q: 'A sound first step when an agent keeps failing a long task is to:', options: ['Increase the temperature', 'Inspect the trace of its steps to find where it went wrong', 'Remove all tools', 'Switch to a smaller model'], answer: 1, explain: 'Traces show which decision or tool result caused the failure.' },
  // Inference
  { topic: 'Inference Eng.', q: 'The KV cache speeds up autoregressive decoding by:', options: ['Storing keys and values of earlier tokens so they are not recomputed for each new token', 'Caching the final answers to repeated questions', 'Compressing the vocabulary', 'Skipping attention entirely'], answer: 0, explain: 'Each new token only needs its own keys and values computed.' },
  { topic: 'Inference Eng.', q: 'Continuous batching improves GPU throughput because:', options: ['It waits for the longest request before starting others', 'New requests join the running batch as soon as other requests finish', 'It runs one request at a time', 'It disables the KV cache'], answer: 1, explain: 'Slots freed by finished requests are filled immediately rather than left idle.' },
  { topic: 'Inference Eng.', q: 'Quantizing a model from 16-bit to 4-bit weights mainly:', options: ['Increases accuracy', 'Reduces memory and can speed up inference, at some cost in accuracy', 'Increases the context window', 'Removes the need for a GPU in every case'], answer: 1, explain: 'Fewer bits per weight shrink the model; rounding error costs some quality.' },
  { topic: 'Inference Eng.', q: 'Speculative decoding uses a small draft model to:', options: ['Replace the large model permanently', 'Propose several tokens that the large model verifies in one pass', 'Tokenise the input', 'Rank retrieved documents'], answer: 1, explain: 'Accepted draft tokens save large-model steps while the output matches what the large model would produce.' },
  // Evaluation and safety
  { topic: 'Eval & Observability', q: 'Using an LLM as a judge to grade outputs is useful, but it should be:', options: ['Trusted without checks', 'Validated against human judgements on a sample', 'Run at the highest temperature', 'Used only on training data'], answer: 1, explain: 'Judges have biases; calibrating against human labels shows whether the scores can be trusted.' },
  { topic: 'Eval & Observability', q: 'An evaluation set is most useful when it:', options: ['Is the same data used for fine-tuning', 'Reflects the real tasks and failure cases the system will meet', 'Contains only easy examples', 'Changes on every run'], answer: 1, explain: 'Representative, stable cases make scores meaningful and comparable over time.' },
  { topic: 'Safety & Security', q: 'A prompt injection attack works by:', options: ['Stealing model weights', 'Placing instructions in content the model reads so it follows them instead of the developer’s', 'Overloading the GPU', 'Corrupting the tokenizer'], answer: 1, explain: 'Untrusted text is treated as instructions unless the system separates data from commands.' },
  // Multimodal, infrastructure, frontier, career
  { topic: 'Multimodal AI', q: 'A diffusion model generates an image by:', options: ['Predicting pixels left to right like text', 'Starting from noise and removing it step by step', 'Retrieving the nearest stored image', 'Sorting patches by brightness'], answer: 1, explain: 'It learns to reverse a gradual noising process.' },
  { topic: 'AI Infrastructure', q: 'GPUs suit deep learning better than CPUs mainly because they:', options: ['Have a higher clock speed per core', 'Run many simple operations in parallel, which matrix arithmetic needs', 'Use less power in every case', 'Store more data on disk'], answer: 1, explain: 'Thousands of cores apply the same operation to many numbers at once.' },
  { topic: 'Career Prep', q: 'In an AI system design interview, the strongest opening move is usually to:', options: ['Name the largest model available', 'Clarify the requirements: users, scale, latency, quality bar and constraints', 'Start drawing the database schema', 'Propose fine-tuning immediately'], answer: 1, explain: 'Requirements decide every later trade-off, so they come first.' },
];
