// Generated by scripts/build-viz-usage.mjs
export const vizUsage = {
 "temperature": [
  "six-words-of-ai-engineering",
  "math-behind-cross-entropy-loss",
  "what-is-generative-ai",
  "how-does-temperature-control-llm-output",
  "small-language-models-slms",
  "how-does-knowledge-distillation-work",
  "how-does-llm-watermarking-work"
 ],
 "agent-loop": [
  "six-words-of-ai-engineering",
  "agentic-rag",
  "ai-agent",
  "ai-agent-loop",
  "react-agent",
  "ai-subagents",
  "how-do-computer-use-agents-work",
  "harness-engineering-in-ai",
  "what-is-loop-engineering",
  "how-does-claude-code-work",
  "how-does-cursor-work",
  "ai-agent-evaluation"
 ],
 "quantization": [
  "six-words-of-ai-engineering",
  "llm-inference-optimization",
  "kv-cache-compression",
  "how-does-model-quantization-work",
  "android-tensorflow-lite-machine-learning-example"
 ],
 "gradient-descent": [
  "machine-learning",
  "math-behind-gradient-descent",
  "math-behind-backpropagation",
  "how-does-fine-tuning-work",
  "proximal-policy-optimization-ppo"
 ],
 "embedding-space": [
  "supervised-vs-unsupervised-learning",
  "what-are-embeddings",
  "how-does-a-vector-database-work",
  "how-does-semantic-search-work",
  "joint-embedding-predictive-architecture-jepa"
 ],
 "linear-vs-logistic": [
  "linear-regression-vs-logistic-regression"
 ],
 "precision-recall": [
  "precision-vs-recall",
  "llm-evaluation"
 ],
 "loss-l1-l2": [
  "l1-and-l2-loss-functions"
 ],
 "regularization": [
  "regularization-in-machine-learning"
 ],
 "rl-gridworld": [
  "reinforcement-learning",
  "decoding-deep-rl-from-human-preferences",
  "reinforcement-learning-from-human-feedback-rlhf",
  "proximal-policy-optimization-ppo",
  "how-do-world-models-work"
 ],
 "contrastive": [
  "contrastive-learning",
  "how-do-image-embeddings-work",
  "joint-embedding-predictive-architecture-jepa"
 ],
 "neuron": [
  "bias-in-artificial-neural-network",
  "feed-forward-networks-in-llms"
 ],
 "dropout": [
  "dropout-in-neural-networks"
 ],
 "normalization": [
  "batch-normalization-vs-layer-normalization",
  "rmsnorm-root-mean-square-layer-normalization",
  "decoding-transformer-architecture"
 ],
 "rnn-vs-transformer": [
  "recurrent-neural-network",
  "how-do-rnns-and-transformers-differ",
  "evolution-of-llm-architecture"
 ],
 "gpu-parallel": [
  "how-does-pytorch-work",
  "how-does-the-machine-learning-library-tensorflow-work",
  "how-does-tensorrt-llm-work",
  "how-does-a-gpu-work-for-deep-learning"
 ],
 "top-k-top-p": [
  "autoregressive-models",
  "how-do-top-k-and-top-p-sampling-work"
 ],
 "causal-mask": [
  "autoregressive-models",
  "causal-masking-in-attention",
  "how-does-sliding-window-attention-work",
  "kv-cache-in-llms"
 ],
 "kv-cache": [
  "autoregressive-models",
  "grouped-query-attention",
  "llm-inference-optimization",
  "prefill-vs-decode-llm-inference-optimization",
  "kv-cache-in-llms",
  "kv-cache-compression",
  "how-does-vllm-work"
 ],
 "tokenizer-bpe": [
  "bpe-in-llms"
 ],
 "vector-similarity": [
  "what-are-embeddings",
  "how-does-a-vector-database-work",
  "how-does-semantic-search-work",
  "how-does-semantic-caching-work",
  "how-do-image-embeddings-work"
 ],
 "multi-head": [
  "decoding-transformer-architecture",
  "self-attention-in-transformers",
  "multi-head-attention-in-transformers",
  "grouped-query-attention"
 ],
 "attention-heatmap": [
  "encoder-vs-decoder-in-transformers",
  "evolution-of-llm-architecture",
  "how-do-attention-sinks-work",
  "how-does-prefix-tuning-work"
 ],
 "qkv-math": [
  "self-attention-in-transformers",
  "math-behind-attention-qkv",
  "decoding-flash-attention",
  "llm-inference-optimization"
 ],
 "rope": [
  "math-behind-rope-rotary-position-embedding"
 ],
 "streaming": [
  "how-does-token-streaming-work",
  "how-do-diffusion-language-models-dlms-work",
  "prefill-vs-decode-llm-inference-optimization",
  "http-request-long-polling-websocket-sse"
 ],
 "lost-in-middle": [
  "lost-in-the-middle-problem-in-llms",
  "recursive-language-models",
  "context-engineering"
 ],
 "moe-router": [
  "evolution-of-llm-architecture",
  "mixture-of-experts"
 ],
 "gqa": [
  "grouped-query-attention",
  "llm-inference-optimization",
  "kv-cache-compression"
 ],
 "sliding-window": [
  "how-does-sliding-window-attention-work"
 ],
 "llm-routing": [
  "small-language-models-slms",
  "jev-and-system-one-models-explained",
  "llm-routing"
 ],
 "diffusion": [
  "how-do-diffusion-language-models-dlms-work",
  "diffusion-models"
 ],
 "guardrails": [
  "jev-and-system-one-models-explained",
  "how-do-llm-guardrails-work",
  "prompt-injection-in-llms"
 ],
 "lora": [
  "lora-low-rank-adaptation-of-llms"
 ],
 "prompt-caching": [
  "how-does-prompt-caching-work"
 ],
 "ann-search": [
  "how-does-a-vector-database-work",
  "how-does-approximate-nearest-neighbor-ann-search-work",
  "how-does-semantic-search-work"
 ],
 "hybrid-search": [
  "how-does-hybrid-search-work"
 ],
 "chunking": [
  "chunking-strategies-for-rag",
  "how-does-cursor-work"
 ],
 "semantic-cache": [
  "how-does-semantic-caching-work"
 ],
 "speculative-decoding": [
  "how-does-cursor-work",
  "speculative-decoding",
  "decoding-medusa",
  "decoding-eagle"
 ],
 "paged-attention": [
  "paged-attention-in-llms",
  "how-does-vllm-work"
 ],
 "continuous-batching": [
  "continuous-batching-in-llms",
  "how-does-vllm-work",
  "how-does-sglang-work",
  "how-does-tensorrt-llm-work"
 ]
};
