// Writes src/course/videos.js: the YouTube video for each lesson.
// IDS lists one entry per lesson, in curriculum order: a YouTube id, "-" when the
// lesson has no video, or "!id" when the video exists but is still a draft on
// YouTube (it is left out until it is published; then remove the "!").
// Run `node scripts/build-videos.mjs --check` to also confirm with YouTube that
// every video can be embedded.
import fs from 'node:fs';
import { allLessons } from '../src/course/curriculum.js';

const IDS = `Va1vx7DTbqo,CVJYIkY-JAk,B8K1tr2DprQ,cLCU1sWk3gk,5KUKYOo1Oek,5iIQE98ok0k,yrPwOGFmy_o,7GO58y7QLhI,LYT9QnGgwUo,G8Fzi54Knz4,Gm8Caw_XLL4,hTLa5-Xgfq0,-,bRkJLgrBxLQ,FwTNlcIKLsU,_cm0poXxHhM,l2i2TG4apww,rE-MuBa09SY,JoFpOHIkU-8,O4kbe0NB3po,R71RmjmXXtc,BNvsr0P6c9k,g80EnJr7bS0,3e7I5LMqPcg,_zUuv_L5Hf4,nQa4HmmwIT0,vF1maq5dS9k,0-q5pl7q_GI,BagaUHpsA5o,2Z1JqEcFq3k,C9R_oSz7Ylo,nXI-aj7x7Y0,JbmiCTcdD0g,rWXF1AVTp4o,fRmkatn6xX8,oYlihLdgj-s,8ZNTuKon0fs,t9fLSDO1ryc,6fYciG7ua8A,xSbHSmCdPIM,p1EHKQPJIhE,H3M5cuuASdg,CzhVT7IuN8g,v-_3SFNOLkc,fF4bTJeYlXE,c6FGvSp_AcM,yJlvIgleY9A,IAk48X_DvRI,XQEccETpRlE,azpZMXeM1yE,Flag_w81pZ8,ngv7xmTLjB4,srrJDpKbxmQ,BTOQtk80mzQ,ShwwfJnPWlI,Rx1pJrmkpYQ,a6mpMw6b1c0,58yBRx9HHKo,bAN1Q7CbKO8,rayllgDX_CI,z17dq3MQ8Fk,kX6fv8vSrWk,LAlnKbz-KrE,_Td7xFwpC8A,dlP0yZgxhBw,DP2XXXhWLo0,bj0xyNtiD3w,Abay1KtUEiU,PRQx0PCtyMw,OIN3wsmqVPg,gW59ua_7Kw0,XA1_LZeFGcU,WQLjS5UIE-Y,xJ4h44tP9oM,x_oTlgdTXx8,
I-orGgZZ77o,xmaplc8A5W0,84UcTJiF76M,eothPwRXEyY,d4YJ0PqhLno,QFf92vknlEs,rTi3gFEopTo,CTPYXmTJhVQ,kSf2sOmWXUc,o8a-46HzgsY,eq5tWHCS2Pg,eIwadYpnfAE,RWlQzmZOEGM,ZOcP9RitAZ0,gB4Mc29KE1c,82qaJ7AwRC0,CBWgb8Y7MuA,Vmt1y8wZe14,B5fxvsgRgRo,04BBDlzWfaE,xlvqMnXcmn4,f8M9XJ6s1js,zZjvF_YINSI,CH4N_Z-FA5s,DIWdx8Xey2k,AsTkIxOKLwY,P6HNXffam0I,9ABHaGJru8E,ffVESFsV0FM,Q1M3s6_Oy2o,O8thEusPmjE,o8hW1MNgJhE,xpq3a0WA4dY,-,u25v-k5fmkY,9WJqfQhzdn8,!wbj_flzkqmw,!SyJae-uVlcw,Mai1s50HW50,!D7jPZVvkb5c,lkTY65Lxxmo,tPn_BHC1atM,Qjo4cu8gydE,gp5tFTbca6I,uM5rJ-BwdJs,KmEM1Tug7cY,A7Udk-vUozI,x9NMET8pJz4,_VLCKuuenL0,r5wTPNsLsgM,KlzKQNmrT6Y,Npq05m-h18k,cCCBnn86Y4o,_ZmCbCLpMkU,7Xf0ZuyyvzE,NLI8mrkQEwo,lHFTc8wNPoA,dKHLk6TH1ls,-cr5uhkkd3I,ukdTB18Xg4I,73AwNM2HagA,FxsWOKO9THA,YuRIDTsEKT0,2US-HdZxBbE,vep3yia1ihA,xew70JqWuOo,jH-AfCZXEkw,ZAgn1naijIA,0WV-pp-8Wtg,1M9eTuUvFQU,tJ7X0TijDik,m8QVSQc6brE,Ypcui6OpQOA,-`.replace(/\s/g, '').split(',');

if (IDS.length !== allLessons.length) throw new Error(`expected ${allLessons.length} entries, got ${IDS.length}`);
const videos = {}, missing = [], drafts = [];
allLessons.forEach((l, i) => {
  const v = IDS[i];
  if (v === '-') missing.push(`${l.num} ${l.title}`);
  else if (v.startsWith('!')) drafts.push(`${l.num} ${l.title}`);
  else videos[l.id] = v;
});
if (new Set(Object.values(videos)).size !== Object.keys(videos).length) throw new Error('a video id is used twice');

if (process.argv.includes('--check')) {
  const bad = [];
  for (const [lesson, id] of Object.entries(videos)) {
    const r = await fetch(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`);
    if (!r.ok) bad.push(`${lesson} ${id} (${r.status})`);
  }
  console.log(bad.length ? `NOT embeddable:\n${bad.join('\n')}` : `all ${Object.keys(videos).length} videos can be embedded`);
}

fs.writeFileSync('src/course/videos.js', `// Generated by scripts/build-videos.mjs. Do not edit.\n// The YouTube video that goes with each lesson, by lesson id.\nexport const lessonVideos = ${JSON.stringify(videos)};\n`);
console.log(`wrote videos.js: ${Object.keys(videos).length} lessons with a video`);
console.log(`no video (${missing.length}): ${missing.join(' | ')}`);
console.log(`draft on YouTube (${drafts.length}): ${drafts.join(' | ')}`);
