import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import ExplodedCore from './ExplodedCore';
import { modules, allLessons } from './course/curriculum';
import { TrackShowcase } from './Tracks';
import { BRAND, PROGRAM } from './brand';
import LogoMark from './LogoMark';

const scenes=[
  {eyebrow:'01 / THE WHOLE',title:['See the system.','Then go inside.'],copy:'Learn AI engineering, machine learning and deep learning, from the first data point to the LLM systems behind every answer.',link:'/curriculum',cta:'Explore The Curriculum'},
  {eyebrow:'02 / DATA LAYER',title:['One model.','Many moving parts.'],copy:'Watch the core open as data and learned patterns separate into visible layers.',link:'/module/ml-foundations',cta:'Begin With ML Foundations'},
  {eyebrow:'03 / MODEL LAYER',title:['Connections shape','every answer.'],copy:'Follow tokens, embeddings, and attention as a language model builds context.',link:'/module/transformers',cta:'Explore Transformers'},
  {eyebrow:'04 / SERVING LAYER',title:['From one prompt','to a running system.'],copy:'Trace retrieval, tools, prefill, decode, and memory all the way to production.',link:'/module/inference',cta:'See Inference Engineering'}
];

function Arrow(){return <span aria-hidden="true">↗</span>}
function AnimatedTitle({lines,as:Tag='h1'}){let count=0;return <Tag className="story-title" aria-label={lines.join(' ')}>{lines.map((line,lineIndex)=><span className={'title-line '+(lineIndex?'muted':'')} aria-hidden="true" key={lineIndex}>{line.split(' ').map((word,wordIndex)=><React.Fragment key={wordIndex}>{wordIndex>0&&' '}<span className="title-word">{[...word].map((character,i)=>{const delay=count++;return <span className="title-character" style={{'--character-delay':`${delay*19}ms`}} key={i}>{character}</span>})}</span></React.Fragment>)}</span>)}</Tag>}
function Reveal({children,className=''}){const ref=useRef();useEffect(()=>{const el=ref.current;const ob=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){el.classList.add('is-visible');ob.disconnect()}},{threshold:.12});ob.observe(el);return()=>ob.disconnect()},[]);return <div ref={ref} className={`cinematic-reveal ${className}`}>{children}</div>}
export default function CinematicHome(){
  const storyRef=useRef(null),[progress,setProgress]=useState(0);
  useEffect(()=>{let raf=0;const update=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const el=storyRef.current;if(!el)return;const rect=el.getBoundingClientRect();const length=Math.max(1,el.offsetHeight-innerHeight)*.88;setProgress(Math.min(1,Math.max(0,-rect.top/length)))})};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();return()=>{cancelAnimationFrame(raf);removeEventListener('scroll',update);removeEventListener('resize',update)}},[]);
  const current=Math.min(3,Math.floor(progress*4));
  const frame=Math.round(progress*120);
  const goToFrame=(target,instant=false)=>{const el=storyRef.current;if(!el)return;const top=el.getBoundingClientRect().top+window.scrollY;window.scrollTo({top:top+(el.offsetHeight-innerHeight)*.88*(target/120),behavior:instant||matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})};
  const replay=()=>{(document.scrollingElement||document.documentElement).scrollTop=0;setProgress(0)};
  return <><main className="cinematic-home"><section ref={storyRef} className="story-scroll"><div className="story-sticky"><ExplodedCore frame={frame}/><div className="story-vignette"/><div className="story-noise"/>
    <div className="story-topline"><span>{PROGRAM.toUpperCase()} · 3 TRACKS · {allLessons.length} LESSONS</span></div>
    {scenes.map((scene,i)=><div className={'story-scene scene-'+i+' '+(i===current?'is-active':'')} key={i} aria-hidden={i!==current}><div className="story-eyebrow"><span className="tiny-line"/>{scene.eyebrow}</div><AnimatedTitle lines={scene.title} as={i?'h2':'h1'}/><p>{scene.copy}</p><div className="story-actions"><Link className="story-primary" to={scene.link} tabIndex={i===current?0:-1}>{scene.cta} <Arrow/></Link>{i===0&&<Link className="story-secondary" to="/guide" tabIndex={i===current?0:-1}>Read The Course Guide <span>→</span></Link>}</div></div>)}
    <div className="story-chapters" aria-label="Story chapters">{['CORE','DATA','MODEL','SERVING'].map((label,i)=><button key={label} className={i===current?'active':''} onClick={()=>goToFrame(i*40)} aria-label={`Go to ${label.toLowerCase()} scene`}><span>{String(i+1).padStart(2,'0')}</span><i/>{label}</button>)}</div>
    <div className="story-bottom"><button className="replay-control" onClick={replay} aria-label="Replay the 3D sequence from the beginning">↺ REPLAY SEQUENCE</button></div>
  </div></section>
  <section className="cinematic-intro"><Reveal><div className="cinematic-kicker">01 / LEARNING, REIMAGINED</div><div className="intro-grid"><h2>The invisible<br/>becomes <i>visible.</i></h2><div><p>Most courses explain AI after they introduce the jargon. The {PROGRAM} starts with the thing you can see: a question, a moving system, and a clear mental model.</p><p>Then you go deeper. Plain language becomes engineering detail, and every concept connects to the next.</p><Link to="/curriculum" className="cinematic-text-link">See All {allLessons.length} Lessons <Arrow/></Link></div></div></Reveal><div className="principles"><Reveal><span>01 / WATCH IT</span><strong>See the mechanism.</strong><p>Animated systems make abstract ideas concrete.</p></Reveal><Reveal><span>02 / MOVE IT</span><strong>Change a variable.</strong><p>Experiment with tokens, context, and memory.</p></Reveal><Reveal><span>03 / UNDERSTAND IT</span><strong>Connect the layers.</strong><p>Go from intuition to real engineering.</p></Reveal></div></section>
  <section className="cinematic-tracks-pick"><Reveal><div className="cinematic-kicker">02 / THREE TRACKS</div><div className="path-heading"><h2>Choose your<br/><i>learning track.</i></h2><p>Start with machine learning and deep learning, go straight into generative AI engineering, or take the complete path with career preparation. Every track comes with its own labs.</p></div></Reveal><Reveal><TrackShowcase/><Link to="/pricing" className="cinematic-text-link">Compare Plans And Pricing <Arrow/></Link></Reveal></section>
  <section className="cinematic-path"><Reveal><div className="cinematic-kicker">03 / THE ROADMAP</div><div className="path-heading"><h2>One universe.<br/><i>Nineteen modules forward.</i></h2><p>Start with machine-learning foundations. Go inside the Transformer, build RAG systems and agents, then serve, evaluate, secure and design production AI. Every lesson ends with a quiz.</p></div></Reveal><div className="cinematic-tracks">{modules.map((t,i)=><Reveal key={t.id}><Link to={`/module/${t.id}`} className="cinematic-track" style={{'--track':t.accent}}><span className="track-ordinal">{String(t.number).padStart(2,"0")} / {modules.length}</span><div className="track-constellation"><div className="track-center">{t.icon}</div><span className="track-star a"/><span className="track-star b"/><span className="track-star c"/><span className="track-star d"/></div><div className="track-words"><small>{t.stage.toUpperCase()} · {t.lessons.length} LESSONS</small><h3>{t.title}</h3><p>{t.intro[0]}</p></div><div className="track-open">EXPLORE MODULE <Arrow/></div></Link></Reveal>)}</div></section>
  <section className="cinematic-spotlight"><Reveal><div className="spotlight-copy"><div className="cinematic-kicker">04 / INTERACT WITH THE IDEA</div><h2>Make sense of<br/><i>what moves.</i></h2><p>Choose a word in the attention map. Watch which other words matter. Then learn the mechanics behind the movement.</p><Link className="story-primary" to="/module/transformers">Enter The Transformer Module <Arrow/></Link></div><div className="spotlight-visual"><div className="spotlight-grid"/><div className="spotlight-word one">the</div><div className="spotlight-word two">cat</div><div className="spotlight-word three">slept</div><div className="spotlight-word four">because</div><div className="spotlight-word five">it</div><svg viewBox="0 0 700 420" preserveAspectRatio="none" aria-hidden="true"><path d="M475 200 Q350 100 200 245"/><path d="M475 200 Q400 310 315 255"/><path d="M475 200 Q490 275 585 250"/></svg><div className="spotlight-caption">ATTENTION / CONTEXT FLOW <span>LIVE CONCEPT</span></div></div></Reveal></section>
  <section className="cinematic-ending"><div className="ending-halo"/><Reveal><div className="cinematic-kicker">THE NEXT STEP IS YOURS</div><h2>Build your<br/><i>understanding.</i></h2><p>Start from zero. Follow the connections. See how AI actually works.</p><Link className="story-primary" to="/lesson/six-words-of-ai-engineering">Start Lesson {allLessons[0].num} <Arrow/></Link></Reveal></section></main><footer className="cinematic-footer"><div className="footer-brand"><LogoMark className="footer-mark"/>{BRAND}</div><div><Link to="/curriculum">CURRICULUM</Link><Link to="/pricing">PRICING</Link><Link to="/glossary">GLOSSARY</Link><Link to="/dashboard">MY LEARNING</Link></div><span>© {new Date().getFullYear()} {BRAND.toUpperCase()}</span></footer></>;
}

